# Generated by Django 5.0.1 on 2024-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.BooleanField(verbose_name='Male')),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_joining', models.DateField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
