# Generated by Django 5.0.1 on 2024-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_alter_student_register_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_register',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
