# Generated by Django 5.0.1 on 2024-02-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0003_alter_student_register_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
