# Generated by Django 5.0.1 on 2024-02-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0004_alter_student_register_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_register',
            table='studentRegister',
        ),
    ]
