# Generated by Django 5.0.1 on 2024-02-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0005_alter_student_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_register',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/'),
        ),
        migrations.AlterModelTable(
            name='student_register',
            table='resume',
        ),
    ]
